version: 2.1.{build}
max_jobs: 1
image: Visual Studio 2015
clone_folder: C:\prj\test-appveyor

build_script:
- ps: cd C:\prj\test-appveyor
- ps: .\appveyor_windows_steps.ps1

after_build:
    7z a .\win_complie-2.1.%APPVEYOR_BUILD_NUMBER%.zip ..\compiled_pyd\*

artifacts:
- path: win_complie-2.1.%APPVEYOR_BUILD_NUMBER%.zip

environment:
  my_variable:
    secure: EtPzN/tNyp4noOA6WEC9WmAXJT3sWa7/E9Ba0Wv4Fvu+2KSsaOX3VDtgMyYkJjI9

deploy:
  release: win_complie-2.1.%APPVEYOR_BUILD_NUMBER%
  artifact: win_complie-2.1.%APPVEYOR_BUILD_NUMBER%.zip
  prerelease: true
#  description: 'windows compile'
  provider: GitHub
  auth_token:
    secure: 8xnAJH3KJgNNa6fghrbQZ4NoYxJLdOkTtqkeGJyL4gG9lR5bHfpKX039qnAIkFPN
  draft: true

